/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "echo_constants.h"



const echoConstants g_echo_constants;

echoConstants::echoConstants() {
}



