/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef echo_CONSTANTS_H
#define echo_CONSTANTS_H

#include "echo_types.h"



class echoConstants {
 public:
  echoConstants();

};

extern const echoConstants g_echo_constants;



#endif
